ood_set: [docetaxel, AZ841, cytochalasin D, simvastatin, cyclohexamide, latrunculin B, epothilone B, lactacystin]
mol_list: Null
multimodal: False
batch_correction: False
batch_key: Null
add_controls: False

image_path: /pasteur2/u/suyc/CellFlow/IMPA/IMPA_reproducibility/datasets/bbbc021_all
data_index_path: /pasteur2/u/suyc/CellFlow/IMPA/IMPA_reproducibility/datasets/bbbc021_all/metadata/bbbc021_df_all.csv
embedding_path: /pasteur2/u/suyc/CellFlow/IMPA/embeddings/csv/emb_fp.csv

augment_train: True
normalize: True
iter_ctrl: False