python train.py \
    --cell_dataset_name bbbc021 \
    --dataset_mode unaligned_cell \
    --name bbbc_SB \
    --mode sb \
    --lambda_SB 1.0 \
    --lambda_NCE 1.0 \
    --direction AtoB \
    --gpu_ids 0 \
    --cond_dim 1024 \